<div class="register_breadcrumbs">
    <div class="breadcrumbs">
        <ul>
            <li class="home"><a href="<?php echo $this->getUrl(); ?>" title="Go to Home Page">Home</a>
                <span>> </span></li>
            <li class="category4"> Sign In</li>
        </ul>
    </div>
</div>
<div class="wrap_create_login_account">
    <div
        class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?>">        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="fieldset">
            <div class="col2-set">
                <?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                    <div
                        class="col-2 new-users">
                        <?php echo $this->getLayout()->createBlock('customer/form_register')->setTemplate('customer/form/register.phtml')->toHtml(); ?>
                    </div>

                    <!--<iframe id="iframe-login" src="<?php /*echo $this->getUrl('customer/account/create') */?>" width="540" height="700"></iframe>-->
                <?php endif; ?>
                <div class="col-1 registered-users">
                    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
                        <div class="page-title"><h1><?php echo $this->__('Sign In') ?></h1>

                            <p class="required"><?php echo $this->__('*Required') ?></p></div>
                        <ul class="form-list"><input type="hidden" name="form_key"
                                                     value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>"/>
                            <li><label for="email" class="required"><?php echo $this->__('Email Address') ?>
                                    <em>*</em></label>

                                <div class="input-box"><input name="login[username]"
                                                              value="<?php echo $this->escapeHtml($this->getUsername()) ?>"
                                                              id="email" type="text"
                                                              class="input-text required-entry validate-email"
                                                              title="<?php echo $this->__('Email Address') ?>"/></div>
                            </li>
                            <li><label for="pass" class="required"><?php echo $this->__('Password') ?><em>*</em></label>

                                <div class="input-box"><input name="login[password]" type="password"
                                                              class="input-text required-entry validate-password"
                                                              id="pass" title="<?php echo $this->__('Password') ?>"/>
                                </div>
                            </li>                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                            <li class="overflowclear wrap_remember_me">
                                <div class="f-left"><a
                                        href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Forgot Your Password?') ?></a>
                                </div>
                                <div class="f-right"></div>
                            </li>                            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                            <li class="mt40 buttons-set">
                                <button type="submit" class="button" name="send" id="send2">
                                    <span><span><?php //echo $this->__('Login') ?></span></span></button>
                            </li>
                        </ul>                        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>                        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
                            <input name="context" type="hidden"
                                   value="checkout"/>                        <?php endif; ?>                    </form>
                </div>
                <div class="registered-users2">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pupsik_front_end_login')->toHtml(); ?>
                </div>
            </div>
        </div>
        <script
            type="text/javascript">            //<![CDATA[            var dataForm = new VarienForm('login-form', true);            //]]>        </script>
    </div>
</div>

