<?php if ($this->getCheckout()->getStepData('payment', 'complete')): ?>
<dt class="complete">
    <?php echo $this->__('Payment Method') ?><span class="changelink"> <span class="separator">|</span> <a
        href="#payment"
        onclick="checkout.changeSection('opc-payment'); return false;"><?php echo $this->__('Change') ?></a></span>
</dt>
<dd class="complete">
    <?php echo $this->getPaymentHtml(); ?>
</dd>

    <?php $payment =trim(strip_tags($this->getPaymentHtml()));
    $payment_array = explode("-" ,$payment);
    $current_payment_method =  trim($payment_array[0]);
    $_SESSION["payment_method_checkout"] = "";
    if($current_payment_method=="Internet Banking/ATM transfer"){

        $_SESSION["payment_method_checkout"] = $current_payment_method;
    }
    else {
        $_SESSION["payment_method_checkout"] = "";
    };

    ?>
<?php else: ?>
<dt>
    <?php echo $this->__('Payment Method') ?>
</dt>
<?php endif; ?>

