<?php


if ($_item):
?>
    <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
        <?php if (!$_item->getRequiredOptions()): ?>
            <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
        <?php endif; ?>
    <?php endif; ?>
    <div class="item-info">
        <a href="<?php echo $this->getProductUrl($_item) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(100) ?>" width="100" height="100" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
        <div class="product-details">
            <h3 class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
            <?php echo $this->getPriceHtml($_item, true, '-related') ?>
            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <p><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></p>
            <?php endif; ?>
        </div>
    </div>
<?php endif;?>
