<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.unveil.js'); ?>"></script>


<script type="text/javascript">
    jQuery(document).ready(function() {
        jQuery(".crosssell img").unveil();
    });

</script>
<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
$_helper = $this->helper('catalog/output');
?>
<?php if($this->getItemCount()): ?>
<div class="clearer"></div>
<div class="box-collateral crosssell">
    <div class="box-title">
        <h2><?php echo $this->__('Don’t forget to add these great deals to your cart!') ?></h2>
    </div>
    <ul class="products-grid bxslider">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item">
            <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_item, 'small_image'), null, true) ?>" class="product-image" style="height: 155px">

                <img src="<?php echo $this->getSkinUrl('images/loader.gif') ?>" data-src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(155); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_item, 'small_image'), null, true) ?>" />
            </a>

            <?php if(!$_item->isSaleable()): ?>
                <p class="sold-out"><?php echo $this->__("Sold Out")?></p>
            <?php endif; ?>

            <h2 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->stripTags($_item->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_item, $_item->getName(), 'name') ?></a></h2>
            <?php if (Mage::getStoreConfig('featuredproducts/general/price_visible')): ?>
                <?php echo $this->getPriceHtml($_item, true, '-upsell') ?>
            <?php endif; ?>

            <?php if (!$_item->isSaleable() && $_item->getTypeId() === 'simple'):?>
                <a href="<?php echo $_item->getProductUrl() ?>">
                    <?php echo $this->__("+Notify when back in stock")?>
                </a>
            <?php elseif($_item->getTypeId() === 'bundle' || $_item->getTypeId() === 'configurable' || $_item->getTypeId() === 'grouped'):?>
                <a class="c-09c hul" href="<?php echo $_item->getProductUrl() ?>">
                    <?php echo $this->__("+ Select Options")?>
                </a>
            <?php elseif ($_item->getTypeId() === 'simple' && $_item->isSaleable()): ?>
                <a class="c-09c hul csp" onclick='ajaxCartProcessing("<?php echo Mage::helper('checkout/cart')->getAddUrl($_item) ?>","<?php echo $_item->getProductUrl()?>", true)'>
                    <?php echo $this->__("+ Add to Cart")?>
                </a>
            <?php endif; ?>
            <?php if($_item->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_item, 'short') ?>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('.bxslider').bxSlider({
            maxSlides: 6,
            slideWidth: 160,
            slideMargin: 40,
            pager: false,
            moveSlides: 1
        });
    });
</script>
<?php endif; ?>
