<?php
$_productCollection = $this->getFeaturedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<span id="rma-please-wait" class="please-wait" style="display:none;">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt=""
                         class="v-middle"/> <?php echo $this->__('Please wait, loading...') ?>
                </span>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">

        <h3 class="featured_title">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pupsik_banner_title_featured_products')->toHtml(); ?>
        </h3>

        <div class="see_all overflowclear">
            <a href="<?php echo $this->getUrl('featured-products'); ?>">
                <p><?php echo __("See All >") ?></p>
            </a>
        </div>

        <?php if ($this->getMode() != 'grid'): ?>
        <?php else: ?>
            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = 4; ?>
            <?php $i = 0;
            $counter = 1;
        foreach ($_productCollection as $_product): ?>
            <?php if ($i++ % $_columnCount == 0): ?>
            <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>"
                   title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                   class="product-image">
                    <img
                        src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(155); ?>"
                        width="155" height="155"
                        alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                </a>

                <?php
                if ($_product->getTypeId() === 'bundle' || $_product->getTypeId() === 'configurable' || $_product->getTypeId() === 'grouped') {
                    $stock = '';
                    foreach ($_product->getTypeInstance(true)->getUsedProducts(null, $_product) as $simple) {
                        $stock += Mage::getModel('cataloginventory/stock_item')->loadByProduct($simple)->getQty();
                    }
                }
                if (!$_product->isSaleable() && ($_product->getTypeId() === 'simple' || $stock == 0)): ?>
                    <p class="sold-out <?php echo $stock . $_product->getTypeId() ?>"><?php echo $this->__("Sold Out") ?></p>
                <?php endif; ?>


                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                            title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                </h2>
                <?php if (Mage::getStoreConfig('featuredproducts/general/price_visible')): ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                <?php endif; ?>

                <?php if (!$_product->isSaleable() && $_product->getTypeId() === 'simple'): ?>
                    <?php
                    if (Mage::getSingleton('customer/session')->isLoggedIn()) {
                        ?>
                        <div class="product-alert">
                            <p class="mess-login">
                                <a href="#inline2" class="hul color-blue csp bttop"
                                   rel="<?php echo $_product->getId(); ?>">
                                    <?php echo __("+ Notify when back in stock") ?>
                                </a>
                            </p>
                        </div>
                        <?php
                    } else {
                        ?>
                        <div class="product-alert">
                            <p class="mess">
                                <a class="hul color-blue csp bttop" rel="<?php echo $_product->getId(); ?>"
                                   href="#inline1">
                                    <?php echo __("+ Notify when back in stock") ?>
                                </a>
                            </p>
                        </div>
                        <?php
                    }
                    ?>

                <?php elseif (!$_product->isSaleable() && $_product->getTypeId() === 'configurable'): ?>
                    <a class="color-blue c-09c hul" href="<?php echo $_product->getProductUrl() ?>">
                        <?php echo $this->__("+ Notify when back in stock") ?>
                    </a>
                <?php elseif ($_product->getTypeId() === 'bundle' || $_product->getTypeId() === 'configurable' || $_product->getTypeId() === 'grouped'): ?>
                    <a class="color-blue c-09c hul" href="<?php echo $_product->getProductUrl() ?>">
                        <?php echo $this->__("+ Select Options") ?>
                    </a>
                <?php elseif ($_product->getTypeId() === 'simple' && $_product->isSaleable()): ?>
                    <a class="color-blue c-09c hul csp"
                       onclick='ajaxCartProcessing("<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>","<?php echo $_product->getProductUrl() ?>")'>
                        <?php echo $this->__("+ Add to Cart") ?>
                    </a>
                <?php endif; ?>
                <?php if ($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>

            </li>
            <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
            </ul>
        <?php endif ?>
        <?php if ($counter == 4) {
            break;
        };
        $counter++;
        endforeach ?>
            <script
                type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
        <?php endif; ?>
    </div>
<?php endif; ?>




<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
    <script type="text/javascript">
        jQuery(".product-alert .mess a").click(function () {
            var base_url = "<?php echo $this->getBaseUrl();?>";
            var id = jQuery(this).attr('rel');
            var encodedUrl = jQuery.base64.encode(window.location);
            var url = base_url + '/productalert/add/stock/product_id/' + id + '/uenc/' + encodedUrl + '/';
            jQuery('.tdu').attr('href', url);
        });

    </script>
<?php else: ?>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            jQuery(".product-alert .mess-login a").fancybox({
                'hideOnOverlayClick':false,
                'hideOnContentClick':false,
                maxWidth: 960,
                'width'				: 700,
                'height'			: 55,
                'showNavArrows' : false,
                'padding'			: 30,
                'titlePosition'		: 'inside',
                'transitionIn'		: 'none',
                'transitionOut'		: 'none',
                'centerOnScroll'    :'true',
                'type'				: 'iframe',
                'autoSize' : false
            });
        });

        (jQuery('.catalog-category-view').find('div.col2-left-layout')).find('ul.messages').css('display', 'none');
        jQuery(".featured_products .product-alert .mess-login a").click(function () {
            var base_url = "<?php echo $this->getBaseUrl();?>";
            var id = jQuery(this).attr('rel');
            jQuery('#rma-please-wait').show();
            jQuery('.category-products').css({'opacity': '0.3'});
            var encodedUrl = jQuery.base64.encode(window.location);
            var url = base_url + '/productalert/add/notifyProducts/product_id/' + id + '/uenc/' + encodedUrl + '/';
            var childProductID = jQuery('.product-alert .mess-login a').first().val();
            if (childProductID) {
                var re = /(\/product_id\/)(\d*)/;
                var myArray = re.exec(url);
                url = url.replace(re, '$1' + childProductID);
            }

            jQuery(this).attr("href",url);

            jQuery('#rma-please-wait').hide();
            jQuery('.category-products').css({'opacity': '1', 'position': 'none'});

        });
    </script>
<?php endif; ?>
<script type="text/javascript">
    //jQuery(".modify").css('margin-left',screen.width/4);
    var h = (screen.height / 3) / 100;
    jQuery(".modify").css('margin-top', h + '%');
    jQuery(".modify").css('margin-left', '5%');
    function linkToNotify() {
        var url = jQuery(".tdu").attr('href');
        var childProductID = jQuery('.product-alert .mess a').first().val();
        if (childProductID) {
            var re = /(\/product_id\/)(\d*)/;
            var myArray = re.exec(url);
            url = url.replace(re, '$1' + childProductID);
        }
        document.location = (url);
    }
</script>
<div style="display: none;">
    <div id="inline1" style="width:600px;height:auto;overflow:auto;">
        <div>
            <p><?php echo __("You need to") ?> <a class="tdu"
                                                  href="<?php echo $this->escapeHtml($this->getSignupUrl()) ?>"><?php echo __("Register an account") ?></a> <?php echo __("with us and") ?>
                <a class="tdu"
                   href="<?php echo $this->escapeHtml($this->getSignupUrl()) ?>"><?php echo __("Sign in") ?></a> <?php echo __("to be notified when the item is back in stock") ?>
            </p>
            <button type="button" class="button btn-continue" onclick="linkToNotify()">
                <span>
                    <span>
                        <?php echo __("Continue"); ?>
                    </span>
                </span>
            </button>
        </div>
    </div>
</div>
<div style="display: none;">
    <div id="inline2" style="width:600px;height:auto;overflow:auto;">

    </div>
</div>