
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>
<?php
$galleryImages = $this->getGalleryImages();
$lbh = '';
if (count($galleryImages) > 1) {
    $gallery = '<div class="more-views">';
    $gallery .= '<h2>' . $this->__('More Views') . '</h2>';
    $gallery .= '<ul>';
    $img_counter = 1;
    foreach ($galleryImages as $_image) {
        $gallery .= '<li>'
                . '<a id="cloud-zoom-gallery' . $i . '" href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '.'data-image="image-'.$img_counter.'"'
                . 'rel="useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) . '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                . '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(73) . '" width="73" height="73" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                . '</a></li>';

        $lbh .= '<a id="image-'.$img_counter.'" data-lightbox="lightbox" href="'.$_image['url'].'">
        <img src="'.$this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile()).'" />
        </a>';

        $img_counter++;
    }
    $gallery .= '</ul></div>';
}
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
    <p class="product-image product-image-zoom">
        <a rel="<?php echo $this->renderCloudOptions(); ?>" <?php echo $this->renderLightboxOptions(); ?> gallery="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
            <?php
            $_img = '<img id="image" src="' . $this->getCloudImage($_product) . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </a>
    </p>
    <?php if (isset($gallery)): ?>
    <div class="more_view_title overflowclear"> <img src="<?php echo $this->getSkinUrl('images/plus_icon.png') ?>" alt="img" />    <span> larger image</span>   |   Roll over image to magnify
    </div>
        <?php echo $gallery; ?>
    <?php endif; ?>
<?php else: ?>
    <p class="product-image">
        <?php
        $_img = '<img src="' . $this->helper('catalog/image')->init($_product, 'image')->resize(566) . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </p>
<?php endif; ?>
<div id="lightbox-hidden" style="display: none">
    <?php echo $lbh?>
</div>

<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery("#image-1").removeAttr("data-lightbox");
        jQuery('.product-img-box .more-views a').click(function(){
            jQuery("#lightbox-hidden > a").attr("data-lightbox","lightbox");
            var $_id = jQuery(this).data('image');
            jQuery("#"+$_id).removeAttr("data-lightbox");
        })
    })
</script>