<div class="footer-container">
    <div class="subcribe_newsletter overflowclear">
        <div class="overflowclear marginauto">
               <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pupsik_footer_babyregistry')->toHtml();
            ?>
        </div>
    </div>
    <div class="wrap_border_footer overflowclear">
    <div class="border_footer"></div>
    </div>
    <div class="footer marginauto">
        <ul class="wrap_footer_info overflowclear">
            <li class="company">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pupsik_footer_companyinfo')->toHtml();
                ?>

            </li>
            <li class="customer-support">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pupsik_footer_customersupport')->toHtml();
                ?>

            </li>
            <li class="shipping">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pupsik_footer_shipping')->toHtml();
                ?>

            </li>

            <li class="no-margin">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('pupsik_footer_testi')->toHtml();
                ?>

            </li>
        </ul>
    </div>
</div>

<div style="display: none;" id="ajax-cart-loading">
    <p id="loading_mask_loader" class="loader"><img alt="Loading..." src="<?php echo $this->getSkinUrl('images/mana_core/m-wait.gif');?>"><br>Please wait...</p>
</div>




<script type="text/javascript">
    var scrolltotop={
        setting: {startline:100, scrollto: 0, scrollduration:1000, fadeduration:[500, 100]},

        controlHTML: '<img src="<?php echo $this->getSkinUrl('images/back_to_top.png') ?>">', //HTML for control, which is auto wrapped in DIV w/ ID="topcontrol"

        controlattrs: {offsetx:5, offsety:5}, //offset of control relative to right/ bottom of window corner

        anchorkeyword: '#top', //Enter href value of HTML anchors on the page that should also act as "Scroll Up" links

        state: {isvisible:false, shouldvisible:false},

        scrollup:function(){

            if (!this.cssfixedsupport) //if control is positioned using JavaScript

                this.$control.css({opacity:0}) ;//hide control immediately after clicking it

            var dest=isNaN(this.setting.scrollto)? this.setting.scrollto : parseInt(this.setting.scrollto);

            if (typeof dest=="string" && jQuery('#'+dest).length==1) //check element set by string exists

                dest=jQuery('#'+dest).offset().top;
            else
                dest=0;
            this.$body.animate({scrollTop: dest}, this.setting.scrollduration);
        },
        keepfixed:function(){
            var $window=jQuery(window);
            var controlx=$window.scrollLeft() + $window.width() - this.$control.width() - this.controlattrs.offsetx;
            var controly=$window.scrollTop() + $window.height() - this.$control.height() - this.controlattrs.offsety;

            this.$control.css({left:controlx+'px', top:controly+'px'})

        },

        togglecontrol:function(){

            var scrolltop=jQuery(window).scrollTop();

            if (!this.cssfixedsupport)

                this.keepfixed();

            this.state.shouldvisible=(scrolltop>=this.setting.startline)? true : false

            if (this.state.shouldvisible && !this.state.isvisible){

                this.$control.stop().animate({opacity:1}, this.setting.fadeduration[0]);

                this.state.isvisible=true

            }

            else if (this.state.shouldvisible==false && this.state.isvisible){

                this.$control.stop().animate({opacity:0}, this.setting.fadeduration[1]);

                this.state.isvisible=false

            }

        },
        init:function(){

            jQuery(document).ready(function($){

                var mainobj=scrolltotop;

                var iebrws=document.all;

                mainobj.cssfixedsupport=!iebrws || iebrws && document.compatMode=="CSS1Compat" && window.XMLHttpRequest ;//not IE or IE7+ browsers in standards mode

                mainobj.$body=(window.opera)? (document.compatMode=="CSS1Compat"? $('html') : $('body')) : $('html,body');

                mainobj.$control=$('<div id="topcontrol">'+mainobj.controlHTML+'</div>')

                    .css({position:mainobj.cssfixedsupport? 'fixed' : 'absolute', bottom:mainobj.controlattrs.offsety, right:mainobj.controlattrs.offsetx, opacity:0, cursor:'pointer'})

                    .attr({title:'Scroll Back to Top'})

                    .click(function(){mainobj.scrollup(); return false})

                    .appendTo('body');

                if (document.all && !window.XMLHttpRequest && mainobj.$control.text()!='') //loose check for IE6 and below, plus whether control contains any text

                    mainobj.$control.css({width:mainobj.$control.width()}); //IE6- seems to require an explicit width on a DIV containing text

                mainobj.togglecontrol();

                $('a[href="' + mainobj.anchorkeyword +'"]').click(function(){

                    mainobj.scrollup();

                    return false

                });

                $(window).bind('scroll resize', function(e){

                    mainobj.togglecontrol();

                })

            })

        }

    };
    scrolltotop.init();
</script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.fancybox-1.3.4.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.hoverIntent.minified.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.base64.js') ?>"></script>

<script type="text/javascript">
    jQuery(document).ready(function(){

        <?php
                         if (!Mage::getSingleton('customer/session')->isLoggedIn()) {
                             ?>
        jQuery(".product-alert .mess a").fancybox({
            'padding'			: 30,
            'titlePosition'		: 'inside',
            'transitionIn'		: 'none',
            'transitionOut'		: 'none',
            'centerOnScroll'    :'true'
        });

        jQuery(".add-to-links a").fancybox({
            'padding'			: 30,
            'titlePosition'		: 'inside',
            'transitionIn'		: 'none',
            'transitionOut'		: 'none',
            'centerOnScroll'    :'true'
        });
<?php } ?>
        /*jQuery(".product-alert .mess a").fancybox({
            'padding'			: 30,
            'titlePosition'		: 'inside',
            'transitionIn'		: 'none',
            'transitionOut'		: 'none',
            'centerOnScroll'    :'true'
        });*/

        /*
         *   popup besseler product
         */
        jQuery(".product-alert .mbestseller_products a").fancybox({
            'padding'			: 30,
            'titlePosition'		: 'inside',
            'transitionIn'		: 'none',
            'transitionOut'		: 'none',
            'centerOnScroll'    :'true'
        });
        /*
         *   popup new product
         */
        jQuery(".product-alert .product_mjustin a").fancybox({
            'padding'			: 30,
            'titlePosition'		: 'inside',
            'transitionIn'		: 'none',
            'transitionOut'		: 'none',
            'centerOnScroll'    :'true'
        });

        /*jQuery(".product-alert2 .mess2 a").fancybox({
            'padding'			: 30,
            'titlePosition'		: 'inside',
            'transitionIn'		: 'none',
            'transitionOut'		: 'none',
            'centerOnScroll'    :'true'
        });*/
    });

</script>

<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery(".main_category").hoverIntent({
            over:
                function(){
                    jQuery(".up_arrow", this).show(0);
                    jQuery(".child_categories", this).show(0);
                },
            out: function(){
                jQuery(".up_arrow" , this).hide(0);
                jQuery(".child_categories" , this).hide(0);
            }
        });
        jQuery(".main_category").each(
            function(){
                var menu_witdh = jQuery(this).outerWidth();
                if( menu_witdh < 128 ){
                    jQuery(this).addClass("more_padding");
                }
            }
        );

        jQuery("#fancybox-wrap #fancybox-close").click(function(){

           window.location.href="<?php echo $this->helper('core/url')->getCurrentUrl(); ?>";
        });

    });
</script>