<?php $_helper = $this->helper('catalog/output');?>
<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <?php $_collectionSize = count($_products->getItems()) ?>

    <div class="category-products">
        <?php //echo $this->getToolbarHtml() ?>
        <?php $_columnCount = 4//$this->getColumnCount(); ?>
        <?php $i=0; foreach ($_products->getItems() as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
            <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(126); ?>" width="126" height="126" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>

                <?php if (Mage::getStoreConfig('featuredproducts/general/price_visible')): ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                <?php endif; ?>
            </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                </ul>
            <?php endif ?>
        <?php endforeach?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

<!--        <div class="toolbar-bottom">-->
<!--            --><?php //echo $this->getToolbarHtml() ?>
<!--        </div>-->
    </div>

<?php else:?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php endif; ?>