<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php echo $this->getToolbarHtml() ?>
    <?php echo $this->getAdditionalHtml() ?>
    <div class="category-products">
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>


        <?php else: ?>

            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = 4; ?>
            <?php $i = 0;
        foreach ($_productCollection as $_product): ?>
            <?php if ($i++ % $_columnCount == 0): ?>
            <ul class="products-grid">
        <?php endif ?>

            <?php
//            $date = date("Y-m-d H:i:s");
//            $todate = $_product['news_to_date'];
//            $fromdate = $_product['news_from_date'];
//            $fromdate2 = DateTime::createFromFormat('Y-m-d H:i:s', $fromdate)->modify('+60 day')->format('Y-m-d H:i:s');
//            $interval = new DateInterval('P2M');
//            if ($todate == "") {
//                $todate = $fromdate2;
//            }

            //if ($date <= $todate) :
                ?>
                <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                    <a href="<?php echo $_product->getProductUrl() ?>"
                       title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                       class="product-image"><img
                            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(152); ?>"
                            width="152" height="152"
                            alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>
                    <?php if(!$_product->isSaleable()): ?>
                        <p class="sold-out"><?php echo $this->__("Sold Out")?></p>
                    <?php endif; ?>

                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                                title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                    </h2>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if (!$_product->isSaleable() &&  $_product->getTypeId() === 'simple'):?>
                        <a href="<?php echo $_product->getProductUrl() ?>" class="color-blue">
                            <?php echo $this->__("+Notify when back in stock") ?>
                        </a>
                    <?php elseif ($_product->getTypeId() === 'bundle' || $_product->getTypeId() === 'configurable' || $_product->getTypeId() === 'grouped'): ?>
                        <a class="color-blue c-09c hul" href="<?php echo $_product->getProductUrl() ?>">
                            <?php echo $this->__("+ Select Options") ?>
                        </a>
                    <?php
                    elseif ($_product->getTypeId() === 'simple' && $_product->isSaleable()): ?>
                        <a class="color-blue c-09c hul csp"
                           onclick='ajaxCartProcessing("<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>","<?php echo $_product->getProductUrl() ?>")'>
                            <?php echo $this->__("+ Add to Cart") ?>
                        </a>
                    <?php endif; ?>

                    <?php if ($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>

                </li>
            <?php //endif; ?>
            <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
            </ul>
        <?php endif ?>
        <?php endforeach ?>
            <script
                type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
        <?php endif; ?>
    </div>
    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
<?php endif; ?>
