
<?php
//    $_productCollection = $this->getLoadedProductCollection();
$_productCollection = Mage::getResourceModel('catalog/product_collection');
$_productCollection->setVisibility(Mage::getSingleton('catalog/product_visibility')->getVisibleInCatalogIds());

$_helper = $this->helper('catalog/output');
//echo count($_productCollection) . " items" ;
//var_dump($_productCollection);
//
//echo  " ===================================================================================================================== " ;
//$collection = Mage::getResourceModel('catalog/product_collection');
//var_dump($collection);
//die;

$todayStartOfDayDate  = Mage::app()->getLocale()->date()
    ->setTime('00:00:00')
    ->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);

$todayEndOfDayDate  = Mage::app()->getLocale()->date()
    ->setTime('23:59:59')
    ->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);

$_productCollection = Mage_Catalog_Block_Product_Abstract::_addProductAttributesAndPrices($_productCollection)
    ->addStoreFilter()
    ->addAttributeToFilter('news_from_date', array('or'=> array(
        0 => array('date' => true, 'to' => $todayEndOfDayDate),
        1 => array('is' => new Zend_Db_Expr('null')))
    ), 'left')
    ->addAttributeToFilter('news_to_date', array('or'=> array(
        0 => array('date' => true, 'from' => $todayStartOfDayDate),
        1 => array('is' => new Zend_Db_Expr('null')))
    ), 'left')
    ->addAttributeToFilter(
        array(
            array('attribute' => 'news_from_date', 'is'=>new Zend_Db_Expr('not null')),
            array('attribute' => 'news_to_date', 'is'=>new Zend_Db_Expr('not null'))
        )
    )
    ->addAttributeToSort('news_from_date', 'desc')
    ->setPageSize($this->getProductsCount())
    ->setCurPage(1) ;
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<?php echo $this->getToolbarHtml() ?>
<?php echo $this->getAdditionalHtml() ?>
<div class="category-products">
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>


<?php else: ?>

<?php $_collectionSize = $_productCollection->count() ?>
<?php $_columnCount = 4; ?>
<?php $i=0; foreach ($_productCollection as $_product): ?>
    <?php if ($i++%$_columnCount==0): ?>
    <ul class="products-grid">
    <?php endif ?>
        <?php
        $p = 1;
        ?>
        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(152); ?>" width="152" height="152" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php if(!$_product->isSaleable()): ?>
                <p class="sold-out"><?php echo $this->__("Sold Out")?></p>
            <?php endif; ?>

            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
            <?php echo $this->getPriceHtml($_product, true) ?>

            <?php if (!$_product->isSaleable() &&  $_product->getTypeId() === 'simple'):?>
                <a href="<?php echo $_product->getProductUrl() ?>">
                    <?php echo $this->__("+Notify when back in stock")?>
                </a>
            <?php elseif($_product->getTypeId() === 'bundle' || $_product->getTypeId() === 'configurable' || $_product->getTypeId() === 'grouped'):?>
                <a class="c-09c hul" href="<?php echo $_product->getProductUrl() ?>">
                    <?php echo $this->__("+ Select Options")?>
                </a>
            <?php elseif ($_product->getTypeId() === 'simple' && $_product->isSaleable()): ?>
                <a class="c-09c hul csp" onclick='ajaxCartProcessing("<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>","<?php echo $_product->getProductUrl()?>")'>
                    <?php echo $this->__("+ Add to Cart")?>
                </a>
            <?php endif; ?>

            <?php if($_product->getRatingSummary()): ?>
            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            <?php endif; ?>

        </li>
    <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
    </ul>
    <?php endif ?>
    <?php endforeach ?>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
<?php endif; ?>
</div>
<div class="toolbar-bottom">
    <?php echo $this->getToolbarHtml() ?>
</div>
<?php endif; ?>
