<?php echo $this->getChildHtml('breadcrumbs') ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->setEscapeMessageFlag(true)->toHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        <div class="product-essential">

                <div class="product-shop">
                    <div class="product-main-info">
                        <div class="product-name">
                            <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
                        </div>
                        <?php $brand_name =  $_product->getAttributeText('brands'); if($brand_name!=""): ?>
                            <?php
                            $brand_url = Mage::helper('brands/data')->getBrandUrlById($_product->getBrands());
                            ?>
                        <div class="product_brand_name overflowclear">
                             By <a href="<?php echo $brand_url?>"><?php echo $brand_name ?></a>
                        </div>
                        <?php endif; ?>

                        <?php //echo $this->getReviewsSummaryHtml($_product, false, true); ?>
                        <?php echo $this->getChildHtml('product_type_data') ?>
                        <?php
                        $_taxHelper = $this->helper('tax');
                        $_store = $_product->getStore();
                        $_convertedFinalPrice = $_store->roundPrice($_store->convertPrice($_product->getFinalPrice()));
                        $current_price = $_taxHelper->getPrice($_product, $_convertedFinalPrice);
                        $old_price = $_product->getPrice();
                        $saving_money = $old_price - $current_price;
                        $percent_saving_money = round($saving_money/$old_price * 100);
                        if($current_price != $old_price) :?>

                        <div class="wrap_saving_money">
                           <span> You Save:</span>
                            <span class="saving_amount">
                                <?php
                                echo Mage::helper('core')->formatPrice($saving_money , false)  . " (" . $percent_saving_money . "%)";
                                ?>
                            </span>
                        </div>
                        <?php endif; ?>
                        <?php echo ($_product->getCanShowPrice() === false) ? '' : $this->getChildHtml('tierprices'); ?>

                        <?php if (!$this->hasOptions()):?>
                            <div class="add-to-box">
                                <?php if($_product->isSaleable()): ?>
                                    <?php echo $this->getChildHtml('addtocart') ?>
                                <?php else: ?>
                                    <?php echo $this->getChildHtml('alert_urls') ?>
                                <?php endif; ?>
                                <?php echo $this->getChildHtml('addto') ?>
                            </div>
                        <?php else:?>
                            <?php if ($this->getChildChildHtml('container1')):?>
                                <div class="options-container-small">
                                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                                </div>
                            <?php endif;?>
                        <?php endif; ?>
                        <?php if ($this->hasOptions() && $this->getChildChildHtml('container2') ):?>
                            <div class="product-collateral overflowclear">
                                <div class="options-container-big">
                                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                                </div>
                            </div>
                        <?php endif;?>

                        <div class="product_short_description">
                            <?php echo $_product->getShortDescription(); ?>

                        </div>
                    </div>

                    <?php echo $this->getChildHtml('extrahint'); ?>

                    <?php if ($_product->getShortDescription()):?>
                        <div class="short-description std">
                            <h2><?php echo $this->__('Quick Overview') ?></h2>
                            <?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>
                        </div>
                    <?php endif;?>

                </div>

                <div class="product-img-box">
                    <?php echo $this->getChildHtml('media') ?>
                </div>

        </div>

        <div class="clearer"></div>
        <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
            <?php foreach ($detailedInfoGroup as $alias => $html):?>
                <div class="product_detail_description">
                    <h1 class="main_category_title"><?php echo $this->escapeHtml($this->getChildData($alias, 'title')) ?></h1>
                    <?php echo $html ?></div>
            <?php endforeach;?>
        <?php endif; ?>
    </form>
    <?php echo $this->getChildHtml('product_review') ?>
    <p><b><?php echo __("Total"); ?></b></p> <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
    <?php echo $this->getChildHtml('relatedProducts') ?>
    <?php echo $this->getChildHtml('upsell_products') ?>
<!--    --><?php //echo $this->getChildHtml('productTagList') ?>
    <?php echo $this->getChildHtml('product_additional_data') ?>
</div>

<script type="text/javascript">
    //<![CDATA[
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
                form.action = url;
            }
            var e = null;
            try {
                this.form.submit();
            } catch (e) {
            }
            this.form.action = oldUrl;
            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }
        }
    }.bind(productAddToCartForm);

    productAddToCartForm.submitLight = function(button, url){
        if(this.validator) {
            var nv = Validation.methods;
            delete Validation.methods['required-entry'];
            delete Validation.methods['validate-one-required'];
            delete Validation.methods['validate-one-required-by-name'];
            // Remove custom datetime validators
            for (var methodName in Validation.methods) {
                if (methodName.match(/^validate-datetime-.*/i)) {
                    delete Validation.methods[methodName];
                }
            }

            if (this.validator.validate()) {
                if (url) {
                    this.form.action = url;
                }
                this.form.submit();
            }
            Object.extend(Validation.methods, nv);
        }
    }.bind(productAddToCartForm);
    //]]>
</script>

<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.unveil.js'); ?>"></script>
