<?php
/**
 * Setup the JavaScript classes with their required fields
 */
?>
<script type="text/javascript">

    // Pass some data over to vZero integration JS
    var vzero = new vZero(
        'gene_braintree_creditcard',
        '<?php echo $this->getClientToken(); ?>',
        <?php echo $this->is3DEnabled(); ?>,
        false,
        false,
        '<?php echo Mage::getUrl('braintree/checkout/quoteTotal', array('_secure' => Mage::app()->getFrontController()->getRequest()->isSecure())); ?>'
    );

    // Pass some data through to the PayPal integration
    var vzeroPaypal = new vZeroPayPalButton(
        '<?php echo $this->getClientToken(); ?>',
        '<?php echo Mage::app()->getStore()->getFrontendName(); ?>',
        <?php echo $this->getSingleUse(); ?>
    );

    // Init the environment
    vzero.init();

</script>