<?php if ($this->getItems()->getSize()): ?>
    <div class="box-collateral box-related">
        <div class="box-title">
            <strong><span><?php echo $this->__('Related Products') ?></span></strong>
        </div>
        <p class="note"><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#"
                                                                                             onclick="selectAllRelated(this); return false;"><strong><?php echo $this->__('select all') ?></strong></a>
        </p>
        <?php $i = 0;
        foreach ($this->getItems() as $_item): ?>
            <?php if ($i++ % 3 == 0): ?>
                <ul class="products-grid bxslider" id="related-product-list">
            <?php endif ?>
            <li class="item<?php if (($i - 1) % 3 == 0): ?> first<?php elseif ($i % 3 == 0): ?> last<?php endif; ?>">
                <?php if (!$_item->isComposite() && $_item->isSaleable()): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <input type="checkbox" class="checkbox related-checkbox"
                               id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]"
                               value="<?php echo $_item->getId() ?>"/>
                    <?php endif; ?>
                <?php endif; ?>

                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_link, 'small_image'), null, true) ?>" class="product-image">
                    <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(155); ?>" width="155" height="155" alt="<?php echo $this->stripTags($this->getImageLabel($_link, 'small_image'), null, true) ?>" />
                </a>
                <?php if(!$_link->isSaleable()): ?>
                    <p class="sold-out"><?php echo $this->__("Sold Out")?></p>
                <?php endif; ?>

                <h2 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->stripTags($_link->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_link, $_link->getName(), 'name') ?></a></h2>
                <?php if (Mage::getStoreConfig('featuredproducts/general/price_visible')): ?>
                    <?php echo $this->getPriceHtml($_link, true, '-related') ?>
                <?php endif; ?>

                <?php if (!$_link->isSaleable() && $_link->getTypeId() === 'simple'):?>
                    <a href="<?php echo $_link->getProductUrl() ?>">
                        <?php echo $this->__("+Notify when back in stock")?>
                    </a>
                <?php elseif($_link->getTypeId() === 'bundle' || $_link->getTypeId() === 'configurable' || $_link->getTypeId() === 'grouped'):?>
                    <a class="c-09c hul" href="<?php echo $_link->getProductUrl() ?>">
                        <?php echo $this->__("+ Select Options")?>
                    </a>
                <?php elseif ($_link->getTypeId() === 'simple' && $_link->isSaleable()): ?>
                    <a class="c-09c hul csp" onclick='ajaxCartProcessing("<?php echo Mage::helper('checkout/cart')->getAddUrl($_link) ?>","<?php echo $_link->getProductUrl()?>")'>
                        <?php echo $this->__("+ Add to Cart")?>
                    </a>
                <?php endif; ?>



            </li>
            <?php if ($i % 3 == 0 || $i == $this->getItems()->count()): ?>
                </ul>
            <?php endif ?>
        <?php endforeach ?>
        <script
            type="text/javascript">decorateGeneric($$('.box-related ul.block-content'), ['odd', 'even', 'first', 'last'])</script>

        <script type="text/javascript">
            //<![CDATA[
            $$('.related-checkbox').each(function (elem) {
                Event.observe(elem, 'click', addRelatedToProduct)
            });

            var relatedProductsCheckFlag = false;
            function selectAllRelated(txt) {
                if (relatedProductsCheckFlag == false) {
                    $$('.related-checkbox').each(function (elem) {
                        elem.checked = true;
                    });
                    relatedProductsCheckFlag = true;
                    txt.innerHTML = "<strong><?php echo $this->__('unselect all') ?><\/strong>";
                } else {
                    $$('.related-checkbox').each(function (elem) {
                        elem.checked = false;
                    });
                    relatedProductsCheckFlag = false;
                    txt.innerHTML = "<strong><?php echo $this->__('select all') ?><\/strong>";
                }
                addRelatedToProduct();
            }

            function addRelatedToProduct() {
                var checkboxes = $$('.related-checkbox');
                var values = [];
                for (var i = 0; i < checkboxes.length; i++) {
                    if (checkboxes[i].checked) values.push(checkboxes[i].value);
                }
                if ($('related-products-field')) {
                    $('related-products-field').value = values.join(',');
                }
            }
            //]]>
        </script>
    </div>
<?php endif ?>
