
<?php if(count($this->getItemCollection()->getItems())): ?>
    <?php $_helper = $this->helper('catalog/output'); ?>
<div class="box-collateral box-up-sell">
    <div class="box-title">
        <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
    </div>
    <ul class="products-grid bxslider" id="upsell-product-list">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
                <li class="item">
                    <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_link, 'small_image'), null, true) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(155); ?>" width="155" height="155" alt="<?php echo $this->stripTags($this->getImageLabel($_link, 'small_image'), null, true) ?>" />
                    </a>
                    <?php if(!$_link->isSaleable()): ?>
                        <p class="sold-out"><?php echo $this->__("Sold Out")?></p>
                    <?php endif; ?>

                    <h2 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->stripTags($_link->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_link, $_link->getName(), 'name') ?></a></h2>
                    <?php if (Mage::getStoreConfig('featuredproducts/general/price_visible')): ?>
                        <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                    <?php endif; ?>

                    <?php if (!$_link->isSaleable() && $_link->getTypeId() === 'simple'):?>
                        <a href="<?php echo $_link->getProductUrl() ?>">
                            <?php echo $this->__("+Notify when back in stock")?>
                        </a>
                    <?php elseif($_link->getTypeId() === 'bundle' || $_link->getTypeId() === 'configurable' || $_link->getTypeId() === 'grouped'):?>
                        <a class="c-09c hul" href="<?php echo $_link->getProductUrl() ?>">
                            <?php echo $this->__("+ Select Options")?>
                        </a>
                    <?php elseif ($_link->getTypeId() === 'simple' && $_link->isSaleable()): ?>
                        <a class="c-09c hul csp" onclick='ajaxCartProcessing("<?php echo Mage::helper('checkout/cart')->getAddUrl($_link) ?>","<?php echo $_link->getProductUrl()?>")'>
                            <?php echo $this->__("+ Add to Cart")?>
                        </a>
                    <?php endif; ?>

                </li>
            <?php endif; ?>
        <?php endfor; ?>
    <?php endfor; ?>
    </ul>
</div>
<script>
    jQuery(document).ready(function(){
        jQuery('#upsell-product-list').bxSlider({
            maxSlides: <?php echo $this->getColumnCount() + 1; ?>,
            slideWidth: 160,
            pager: false,
            moveSlides: 1
        });
    })
</script>
<?php endif ?>
