

<div class="total-header-title">Order Summary</div>

<div class="order-summary">
    <?php
    $cart = Mage::getModel('checkout/cart')->getQuote();
    if(count($cart->getAllVisibleItems()) > 0):
    ?>
        <ul>
            <?php
            foreach ($cart->getAllVisibleItems() as $_item) {
//            $productName = $item->getProduct()->getName();
//            $productPrice = $item->getProduct()->getPrice();
                $_product = Mage::getModel('catalog/product')->load($_item->getProduct()->getId());
                ?>
                <li class="item">
                    <a class="product-image" title="<?php echo $this->escapeHtml($_item->getName()) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(75); ?>" width="75" height="75" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" />
                    </a>
                    <div class="product-details">
                        <h3 class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></h3>
                        <div class="product-order-info">
                            <div class="left">
                                <?= $this->__('Qty') ?>: <?= $_item->getQty() ?>
                            </div>
                            <div class="right">
                                <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
                                    <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
                                <?php else: ?>
                                    <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
                                <?php endif; ?>
                            </div>
                            <div class="product-discount">
                                <?php
                                    $current_price = $_product->getFinalPrice();
                                    $old_price = $_product->getPrice();
                                    $saving_money = $old_price - $current_price;
                                    if($current_price != $old_price) :
                                        $discountAmount = Mage::helper('core')->formatPrice($saving_money , false);
                                        echo $this->__('Discount %s applied', $discountAmount);
                                    endif;
                                ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php
            }
            ?>
        </ul>
        <?php
        $current = 60;
        $grandTotal = $cart->getGrandTotal();
        $shippingLeft = $current - $grandTotal;
        if($shippingLeft < 0) $mess = $this->__("Free Shipping now");
        else $mess = $this->__("You are ").$this->helper('core')->formatPrice($shippingLeft , false).$this->__(" away from Free Shipping");
        ?>
        <div class="statistic-data">
            <div>
                <span class="mess-free-shipping c-09c"><?php echo $mess?></span>
            </div>
            <div>
                <select disabled="disabled">
                    <option>Singapore</option>
                </select>
            </div>
            <div>
                <span><b>Shipping</b> <a class="shipping-link">see shipping rates</a></span>
            </div>
            <div>
                <span><b>GST</b></span> <span>(7% inclusive)</span>
            </div>
        </div>
    <?php endif; ?>
</div>
<div class="proceed-check-out">
    <?php if($cart->getShippingAddress()->getShippingInclTax() > 0): ?>
    <div>Subtotal:
        <span class="proceed-price"><?php echo $this->helper('core')->formatPrice($cart->getSubtotal() , false)?></span>
    </div>
    <div>Shipping & Handling <br/>(<?php echo $cart->getShippingAddress()->getShippingDescription() ?>):
        <span class="proceed-price"><?php echo $this->helper('core')->formatPrice($cart->getShippingAddress()->getShippingInclTax() , false)?></span>
    </div>
    <?php endif; ?>
    <div>Total:
        <span class="proceed-price"><?php echo $this->helper('core')->formatPrice($cart->getGrandTotal() , false)?></span>
    </div>
</div>